/** Explicitly reconstruct a stage input from an older reference snapshot, without downstream answers. */
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { WitokPaths } from '../server/src/artifacts/paths.ts';
import { stageById } from '../server/src/run/stages.ts';
import { treeDigest } from './src/diagnostics.ts';

const snapshots = resolve(fileURLToPath(new URL('snapshots', import.meta.url)));
const source = join(snapshots, 'rename-field-plan-diagnostic-v2');
const target = join(snapshots, 'rename-field-intent-reference');
const metadata = JSON.parse(readFileSync(join(source, 'snapshot.json'), 'utf8'));
if (!existsSync(target)) {
  mkdirSync(target);
  // Copy only project source and git base, never the plan/exploration/answers.
  for (const name of ['src', 'test', 'scripts', 'package.json', '.git']) {
    const path = join(source, name);
    if (existsSync(path)) cpSync(path, join(target, name), { recursive: true });
  }
  const sourcePaths = new WitokPaths(source, metadata.slug);
  const paths = new WitokPaths(target, metadata.slug);
  mkdirSync(join(target, '.sdlc', metadata.slug), { recursive: true });
  cpSync(sourcePaths.gates, paths.gates);
  let intent = readFileSync(sourcePaths.intent, 'utf8');
  intent = intent.replace(/(## Что придётся тронуть)[\s\S]*?(?=\r?\n## |$)/u,
    '$1\n\n- ‹path/to/file› — ‹что здесь меняем›\n');
  writeFileSync(paths.intent, intent, 'utf8');
  cpSync(sourcePaths.intentSections, paths.intentSections);
  // Stage 1 approval is retained; stage 2 evidence must be generated by the measured model.
  cpSync(sourcePaths.readiness, paths.readiness);
  writeFileSync(join(target, 'snapshot.json'), JSON.stringify({ ...metadata,
    stoppedAfterStage: 'intent', inputPreparation: {
      kind: 'reference-stage-input', source: 'rename-field-plan-diagnostic-v2', sourceHash: treeDigest(source),
      preparedAt: new Date().toISOString(), retained: ['source', 'gates', 'intent', 'intentSections', 'readiness'],
      withheld: ['exploration', 'clarification', 'plan', 'runtime'],
    },
  }, null, 2) + '\n', 'utf8');
}
const paths = new WitokPaths(target, metadata.slug);
const blockers = stageById('explore').requires.map((requirement) => requirement.check({ paths, chunk: 1, attempt: 1 })).filter(Boolean);
if (blockers.length) throw new Error(blockers.join('; '));
console.log(`Validated ${target}`);
